"""Pull a Google Doc back down and turn it into the Obsidian-flavored summary.md.

This is the inverse of :mod:`recording_summary.gdoc`: it takes the Markdown that
Google Docs exports and rebuilds the local summary — YAML frontmatter, the
``# Recording Summary`` heading, and the generator footer.
"""

import argparse
import difflib
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
from collections import Counter

from .gdoc import (
    FRONTMATTER_RE, META_LABELS, dump_frontmatter, is_rendered, split_frontmatter,
)

# rendered metadata label -> frontmatter key ("講者" -> "speaker")
LABEL_TO_KEY = {label: key for key, label in META_LABELS}

# the "---" + "*Generated by ... *" block cli.py appends to every summary
FOOTER_RE = re.compile(r"\n-{3,}\n(\*Generated by [^\n]*\*)\s*$")

# the same footer as it comes back from Google Docs, which may keep the italic
# line, lose its rule, or both — anchored at the end so a stack of them left by
# an earlier sync can be peeled off one at a time
EXPORTED_FOOTER_RE = re.compile(r"\n*(?:-{3,}[ \t]*\n+)?\*Generated by [^\n]*\*[ \t]*$")

# a horizontal rule left dangling where Google Docs swallowed that footer
TRAILING_RULE_RE = re.compile(r"\n*-{3,}\s*$")

HEADING_RE = re.compile(r"^(?P<hashes>#{2,6})\s+(?P<text>.*\S)\s*$")
ANY_HEADING_RE = re.compile(r"^#{1,6}\s")

# legacy shapes gdoc.promote_headings turns into headings on the way up
BOLD_SECTION_RE = re.compile(r"^\*\*(?P<number>\d+)\.\s*(?P<text>.+?)\*\*\s*$")
BOLD_BULLET_RE = re.compile(r"^[ \t]*[-*+][ \t]+\*\*(?P<text>.+?)\*\*[ \t]*$")

# the model's own restated title, which gdoc.to_gdoc_markdown drops on upload
RESTATED_TITLE_RE = re.compile(r"^#\s+Recording Summary\s*\n+(\*\*(?!\d+\.)[^\n]+\*\*)\s*$",
                               re.MULTILINE)

BULLET_RE = re.compile(r"^(?P<indent>[ \t]*)(?P<marker>[-*+])(?P<gap>[ \t]+)(?P<text>\S.*)$")
ORDERED_RE = re.compile(r"^(?P<indent>[ \t]*)(?P<marker>\d+[.)])(?P<gap>[ \t]+)(?P<text>\S.*)$")

# Google Docs backslash-escapes Markdown punctuation on export ("會議結束\~")
ESCAPE_RE = re.compile(r"\\([!\"#$%&'()*+,\-./:;<=>?@\[\\\]^_`{|}~])")

# ...and writes a soft line break inside a paragraph as a trailing backslash,
# which ESCAPE_RE cannot reach because there is no character after it
HARD_BREAK_RE = re.compile(r"[ \t]*\\(?=\n|$)")

DEFAULT_INDENT = 2

# frontmatter key holding the Google Docs file id this summary syncs with;
# gdoc.py never renders it, so it stays out of the uploaded document
DOC_ID_KEY = "gdoc_id"

# "**講者：** 張三" — the colon may sit inside or outside the bold run, and is
# required, so a bold-only legacy section title is not read as metadata
META_LINE_RE = re.compile(
    r"^\*\*\s*(?P<label>[^*：:]+?)\s*(?:[：:]\s*\*\*|\*\*\s*[：:])\s*(?P<value>.*?)\s*$"
)

# the same field after Google Docs (or a retyping user) lost the bold run; only
# ever tried on a line sitting inside an established metadata block
LOOSE_META_LINE_RE = re.compile(
    r"^(?P<label>[^*：:]{1,16}?)\s*[：:]\s*(?P<value>\S.*?)\s*$"
)


class SyncError(Exception):
    """A failure worth reporting as a message rather than a traceback."""


def _raw_frontmatter(md):
    """The frontmatter exactly as the local file writes it, or None."""
    m = FRONTMATTER_RE.match(md)
    return m.group("yaml") if m else None


def _strip_hard_break(line):
    """Drop the trailing hard-break markers Google Docs round-trips through."""
    return re.sub(r"[ \t]*\\?$", "", line.rstrip())


def list_item(line):
    """Match a bullet or a numbered list item."""
    return BULLET_RE.match(line) or ORDERED_RE.match(line)


def parse_gdoc_header(exported):
    """Split the exported doc into (title, {key: value}, body).

    The metadata block is one paragraph of hard-broken lines, and it is read as
    a whole rather than line by line: a label that lost its bold run in Google
    Docs would otherwise end the block early, dropping every field below it into
    the body as literal text and deleting them from the frontmatter.
    """
    lines = exported.lstrip("\ufeff").split("\n")
    i = 0

    title = None
    while i < len(lines) and not lines[i].strip():
        i += 1
    if i < len(lines):
        m = re.match(r"^#\s+(.*\S)\s*$", lines[i])
        if m:
            title = m.group(1)
            i += 1

    while i < len(lines) and not lines[i].strip():
        i += 1

    end = i
    while end < len(lines) and lines[end].strip() and not ANY_HEADING_RE.match(lines[end]):
        end += 1
    block = [_strip_hard_break(line) for line in lines[i:end]]

    # It is a metadata block only if at least one line still carries its bold
    # label. Inside such a block a line that lost its formatting is read with
    # the looser pattern, and a label the pipeline does not know keys the field
    # under its own name.
    meta = {}
    if any(META_LINE_RE.match(line) for line in block):
        for line in block:
            m = META_LINE_RE.match(line) or LOOSE_META_LINE_RE.match(line)
            if not m:
                continue
            value = m.group("value").strip()
            if value:
                label = m.group("label").strip()
                meta[LABEL_TO_KEY.get(label, label)] = value
        i = end

    return title, meta, "\n".join(lines[i:]).strip()


def merge_frontmatter(local_meta, title, gdoc_meta):
    """Rebuild the frontmatter from the document, which is the source of truth.

    Renaming a label in Google Docs renames the field, adding one adds a field,
    and dropping one drops it. Three things do not come from the document: the
    exact YAML form of an unchanged value (a ``date:`` that loaded as a date
    object stays one rather than being churned into a quoted string), and the
    fields gdoc.py never renders into it — ``gdoc_id`` and any field with no
    value — which are carried forward at the position they held locally.

    A document that yields no metadata at all is treated as a failure to find
    the block rather than a request to delete every field.
    """
    def keep_local_type(key, value):
        if key in local_meta and str(local_meta[key]) == value:
            return local_meta[key]
        return value

    if not gdoc_meta and any(is_rendered(k, v) for k, v in local_meta.items()):
        merged = dict(local_meta) if title is None else {"title": title, **local_meta}
        if title is not None:
            merged["title"] = keep_local_type("title", title)
        return merged

    merged = {}
    if title is not None:
        merged["title"] = keep_local_type("title", title)
    elif "title" in local_meta:
        merged["title"] = local_meta["title"]

    for key, value in gdoc_meta.items():
        merged[key] = keep_local_type(key, value)

    # Put each field the document never carried back where it sat locally:
    # ahead of the first later local field that survived, or at the end.
    order = list(merged)
    local_keys = list(local_meta)
    for key in local_keys:
        if key in merged or key == "title" or is_rendered(key, local_meta[key]):
            continue
        follower = next((k for k in local_keys[local_keys.index(key) + 1:] if k in order), None)
        order.insert(len(order) if follower is None else order.index(follower), key)
        merged[key] = local_meta[key]
    return {key: merged[key] for key in order}


def _bold_section_lines(local_body):
    """Map heading text back to the bold line the local file writes it as."""
    lines = {}
    for line in local_body.split("\n"):
        for pattern in (BOLD_SECTION_RE, BOLD_BULLET_RE):
            m = pattern.match(line)
            if m:
                lines[m.group("text").strip()] = (line, pattern is BOLD_BULLET_RE)
                break
    return lines


def demote_headings(body, local_body):
    """Undo gdoc.promote_headings for summaries that use bold section titles.

    Only headings the local file actually writes as bold are demoted, so files
    that already use real headings keep them. A section *added* in Google Docs
    has no local counterpart; in a file that writes every section bold it is
    given the same shape as its siblings rather than left as a stray heading.
    """
    bold = _bold_section_lines(local_body)
    if not bold:
        return body

    local_lines = local_body.split("\n")
    own_h2 = any(re.match(r"^##\s", line) for line in local_lines)
    own_h3 = any(re.match(r"^###\s", line) for line in local_lines)
    bold_themes = any(is_bullet for _, is_bullet in bold.values())
    marker, gap, _, _ = _list_style(local_body)
    number = 0

    lines = body.split("\n")
    out = []
    i = 0
    while i < len(lines):
        m = HEADING_RE.match(lines[i])
        entry = bold.get(m.group("text")) if m else None
        if m and entry is None:
            level = len(m.group("hashes"))
            if level == 2 and not own_h2:
                number += 1
                entry = (f"**{number}. {m.group('text')}**", False)
            elif level == 3 and not own_h3 and bold_themes:
                entry = (f"{marker}{gap}**{m.group('text')}**", True)
        if entry is None:
            out.append(lines[i])
            i += 1
            continue

        replacement, is_bullet = entry
        numbered = BOLD_SECTION_RE.match(replacement)
        if numbered:
            # Keep the running count in step with the numbers the local file
            # already uses, so a new section follows on from its predecessor.
            number = int(numbered.group("number"))
        out.append(replacement)
        i += 1
        # A bold bullet sits directly above its detail points; the blank line
        # Google Docs puts under the heading would split the list.
        if is_bullet:
            j = i
            while j < len(lines) and not lines[j].strip():
                j += 1
            if j < len(lines) and list_item(lines[j]):
                i = j
    return "\n".join(out)


def _list_style(md):
    """The (marker, gap, ordered gap, indent unit) a document writes lists with."""
    markers, gaps, ordered_gaps, indents = [], [], [], set()
    for line in md.split("\n"):
        m = list_item(line)
        if not m:
            continue
        if BULLET_RE.match(line):
            markers.append(m.group("marker"))
            gaps.append(m.group("gap"))
        else:
            ordered_gaps.append(m.group("gap"))
        width = len(m.group("indent").expandtabs(4))
        if width:
            indents.add(width)

    def common(values, fallback):
        return Counter(values).most_common(1)[0][0] if values else fallback

    return (common(markers, "-"), common(gaps, " "), common(ordered_gaps, " "),
            min(indents) if indents else DEFAULT_INDENT)


def _list_items(md, unit):
    """Every list item in document order as (text, depth, starts_block).

    ``starts_block`` marks an item that opens a fresh list: the first one, or
    one cut off from the item above by a heading or a paragraph. A blank line
    on its own does not break a list.
    """
    found = []
    starts = True
    for line in md.split("\n"):
        m = list_item(line)
        if m:
            found.append((m.group("text").strip(),
                          len(m.group("indent").expandtabs(4)) // unit,
                          starts))
            starts = False
        elif line.strip():
            starts = True
    return found


def _align_depths(local_items, doc_items, doc_has_indent):
    """Decide a depth for each exported item by lining the two lists up.

    Google Docs can come back with every item flattened to a single level, so
    the export's own indentation is often worthless. Diffing the item texts puts
    an edited item back at the depth its local counterpart had, instead of
    stranding it — and its children with it — at the top level.
    """
    matcher = difflib.SequenceMatcher(
        a=[item[0] for item in local_items],
        b=[item[0] for item in doc_items],
        autojunk=False,
    )
    depths = [None] * len(doc_items)
    for tag, i1, i2, j1, j2 in matcher.get_opcodes():
        if tag not in ("equal", "replace"):
            continue
        for offset in range(j2 - j1):
            if i1 + offset < i2:
                depths[j1 + offset] = local_items[i1 + offset][1]

    resolved, previous = [], 0
    for index, depth in enumerate(depths):
        if doc_items[index][2]:
            # The item opens a new list, so there is no item above for it to be
            # a sibling of — a depth from the list before the break would nest
            # a whole new section under its own first line.
            previous = 0
        if depth is None:
            # An item with no counterpart: trust the export when it still
            # carries indentation, otherwise make it a sibling of the one above.
            depth = doc_items[index][1] if doc_has_indent else previous
        resolved.append(depth)
        previous = depth
    return resolved


def restore_bullets(body, local_body):
    """Re-write exported list items in the local file's marker and indent style.

    Google Docs re-markers every bullet and flattens the nesting, so an
    untouched list would otherwise show up as an edit on every line. Depths come
    from the local file via :func:`_align_depths`, clamped so a restored level
    can never skip its parent.
    """
    marker, gap, ordered_gap, unit = _list_style(local_body)
    src_unit = _list_style(body)[3]
    local_items = _list_items(local_body, unit)
    doc_items = _list_items(body, src_unit)
    depths = _align_depths(local_items, doc_items,
                           any(item[1] for item in doc_items))

    out = []
    prev_depth = -1
    seen = 0
    for line in body.split("\n"):
        m = list_item(line)
        if not m:
            out.append(line)
            if line.strip():
                prev_depth = -1
            continue
        depth = max(0, min(depths[seen], prev_depth + 1))
        indent = " " * (unit * depth)
        if BULLET_RE.match(line):
            out.append(f"{indent}{marker}{gap}{doc_items[seen][0]}")
        else:
            # A numbered item keeps its own number — the document decides the
            # ordering — but takes the local file's indent and spacing.
            out.append(f"{indent}{m.group('marker')}{ordered_gap}{doc_items[seen][0]}")
        prev_depth = depth
        seen += 1
    return "\n".join(out)


def _blank_line_habits(md):
    """How the local file spaces its blocks.

    Returns (after a heading, between list items, ahead of a list, after a
    list), each True when the file usually leaves a blank line there.
    """
    lines = md.split("\n")
    after_heading = [0, 0]      # [tight, spaced]
    between_items = [0, 0]
    before_list = [0, 0]
    after_list = [0, 0]
    for i, line in enumerate(lines[:-1]):
        if not line.strip():
            continue
        is_heading = bool(ANY_HEADING_RE.match(line))
        is_item = bool(list_item(line))

        j = i + 1
        while j < len(lines) and not lines[j].strip():
            j += 1
        if j >= len(lines):
            continue
        spaced = j > i + 1

        if is_heading:
            after_heading[spaced] += 1
        elif is_item:
            if list_item(lines[j]):
                between_items[spaced] += 1
            else:
                after_list[spaced] += 1
        elif list_item(lines[j]):
            before_list[spaced] += 1
    return (after_heading[1] > after_heading[0],
            between_items[1] > between_items[0],
            before_list[1] > before_list[0],
            after_list[1] > after_list[0])


def normalize_blank_lines(body, local_body):
    """Space blocks the way the local file does.

    Google Docs exports every block as its own paragraph, so it puts a blank
    line under each heading and between list groups. Left alone those show up
    as edits on a file the pipeline writes tightly.
    """
    spaced_headings, spaced_items, spaced_lists, spaced_after_list = \
        _blank_line_habits(local_body)
    lines = body.split("\n")
    out = []
    i = 0
    while i < len(lines):
        line = lines[i]
        out.append(line)
        i += 1

        if not line.strip():
            continue
        is_heading = bool(ANY_HEADING_RE.match(line))
        is_item = bool(list_item(line))

        j = i
        while j < len(lines) and not lines[j].strip():
            j += 1
        if j == i or j >= len(lines):
            continue
        next_is_item = bool(list_item(lines[j]))

        if is_heading:
            keep_blank = spaced_headings
        elif is_item:
            keep_blank = spaced_items if next_is_item else spaced_after_list
        elif next_is_item:
            keep_blank = spaced_lists
        else:
            keep_blank = True
        if keep_blank:
            out.append("")
        i = j
    return "\n".join(out)


def from_gdoc_markdown(exported, local_md, doc_id=None):
    """Rebuild the Obsidian summary from a Google Docs export."""
    exported = HARD_BREAK_RE.sub("", ESCAPE_RE.sub(r"\1", exported))
    local_meta, local_body = split_frontmatter(local_md)
    title, gdoc_meta, body = parse_gdoc_header(exported)
    meta = merge_frontmatter(local_meta, title, gdoc_meta)
    if doc_id:
        meta[DOC_ID_KEY] = doc_id

    footer = FOOTER_RE.search(local_body)
    if footer:
        # Google Docs usually drops the italic generator line and leaves the
        # bare rule behind, but it sometimes keeps it. Strip whatever came back
        # — including copies an earlier sync appended — before putting the local
        # footer on, so it can never accumulate.
        while True:
            trimmed = EXPORTED_FOOTER_RE.sub("", body)
            if trimmed == body:
                break
            body = trimmed
        body = TRAILING_RULE_RE.sub("", body)
    restated = RESTATED_TITLE_RE.search(local_body)
    if restated and not body.startswith(restated.group(1)):
        body = f"{restated.group(1)}\n\n{body}"
    body = demote_headings(body, local_body)
    body = restore_bullets(body, local_body)
    body = normalize_blank_lines(body, local_body)

    parts = []
    if meta:
        # An untouched header keeps the file's own YAML — comments, quoting and
        # block style included — rather than being churned through safe_dump.
        raw = _raw_frontmatter(local_md)
        unchanged = raw is not None and meta == local_meta and list(meta) == list(local_meta)
        parts.append(f"---\n{raw if unchanged else dump_frontmatter(meta)}\n---")
    parts.append("# Recording Summary")
    parts.append(body.strip())
    if footer:
        parts.append(f"---\n{footer.group(1)}")
    return "\n\n".join(parts).rstrip() + "\n"


def export_doc(doc_id):
    """Export a Google Doc as Markdown via the ``gws`` CLI."""
    params = json.dumps({"fileId": doc_id, "mimeType": "text/markdown"})
    workdir = tempfile.mkdtemp()
    try:
        # gws resolves file arguments relative to the working directory, so run
        # it inside a scratch dir and hand it a bare filename.
        subprocess.run(
            ["gws", "drive", "files", "export", "--params", params, "-o", "exported.md"],
            cwd=workdir, check=True,
        )
        with open(os.path.join(workdir, "exported.md"), encoding="utf-8") as f:
            return f.read()
    except FileNotFoundError:
        raise SyncError("gws not found — install the Google Workspace CLI, or pass "
                        "--from-file with a document you exported yourself.")
    except subprocess.CalledProcessError as e:
        raise SyncError(f"gws could not export {doc_id} (exit {e.returncode}). Check the "
                        f"document id and that your Google credentials are still valid.")
    finally:
        shutil.rmtree(workdir, ignore_errors=True)


def _ask():
    try:
        answer = input("  Apply these changes to the local summary? [y/N] ")
    except (EOFError, KeyboardInterrupt):
        # No one is there to answer — nothing is a safe default to write.
        print(file=sys.stderr)
        return False
    return answer.strip().lower() in ("y", "yes")


def _write_atomically(path, text):
    """Replace the file in one step.

    The summary costs a full transcription and summarization run to produce and
    the Google Doc holds a different format, so a truncating write that fails
    part way would destroy the only usable copy.
    """
    fd, tmp = tempfile.mkstemp(dir=os.path.dirname(os.path.abspath(path)),
                               prefix=".gdoc_sync-", suffix=".tmp")
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as f:
            f.write(text)
        shutil.copymode(path, tmp)
        os.replace(tmp, path)
    except BaseException:
        if os.path.exists(tmp):
            os.unlink(tmp)
        raise


def sync(path, doc_id=None, from_file=None, assume_yes=False,
         exporter=export_doc, confirm=None, out=sys.stdout):
    """Pull the Google Doc back into ``path``. Returns a process exit code."""
    with open(path, encoding="utf-8") as f:
        local = f.read()

    meta, _ = split_frontmatter(local)
    resolved = doc_id or meta.get(DOC_ID_KEY)
    if not from_file and not resolved:
        print(f"No {DOC_ID_KEY} in {path}. Pass --doc-id <id> once and it will be "
              f"recorded in the frontmatter.", file=out)
        return 1

    if from_file:
        with open(from_file, encoding="utf-8") as f:
            exported = f.read()
    else:
        exported = exporter(resolved)

    updated = from_gdoc_markdown(exported, local, doc_id=doc_id)
    if updated == local:
        print(f"{path} is up to date — no changes in the Google Doc.", file=out)
        return 0

    diff = difflib.unified_diff(
        local.splitlines(), updated.splitlines(),
        fromfile=f"{path} (local)", tofile="Google Doc", lineterm="",
    )
    print("\n".join(diff), file=out)
    print(file=out)

    if not assume_yes and not (confirm or _ask)():
        print("Aborted — local file left unchanged.", file=out)
        return 0

    _write_atomically(path, updated)
    print(f"Updated {path}", file=out)
    return 0


def main(argv=None):
    p = argparse.ArgumentParser(
        prog="python3 -m recording_summary.gdoc_sync",
        description="Pull edits made in Google Docs back into the local summary.md",
    )
    p.add_argument("path", help="Local summary markdown file to update")
    p.add_argument("--doc-id", help=f"Google Docs file id (recorded as {DOC_ID_KEY} in the frontmatter)")
    p.add_argument("--from-file", metavar="MD",
                   help="Use an already-exported markdown file instead of calling gws")
    p.add_argument("-y", "--yes", action="store_true", help="Apply without confirming")
    args = p.parse_args(argv)

    try:
        return sync(args.path, doc_id=args.doc_id, from_file=args.from_file,
                    assume_yes=args.yes)
    except SyncError as e:
        print(f"error: {e}", file=sys.stderr)
        return 1
    except OSError as e:
        print(f"error: {e}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
