"""Pull a Google Doc back down and turn it into the Obsidian-flavored summary.md.

This is the inverse of :mod:`video_summary.gdoc`: it takes the Markdown that
Google Docs exports and rebuilds the local summary — YAML frontmatter, the
``# Recording Summary`` heading, and the generator footer.
"""

import argparse
import difflib
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
from collections import Counter

import yaml

from .gdoc import META_LABELS, split_frontmatter

# rendered metadata label -> frontmatter key ("講者" -> "speaker")
LABEL_TO_KEY = {label: key for key, label in META_LABELS}

# the "---" + "*Generated by ... *" block cli.py appends to every summary
FOOTER_RE = re.compile(r"\n-{3,}\n(\*Generated by [^\n]*\*)\s*$")

# a horizontal rule left dangling where Google Docs swallowed that footer
TRAILING_RULE_RE = re.compile(r"\n*-{3,}\s*$")

HEADING_RE = re.compile(r"^(?P<hashes>#{2,6})\s+(?P<text>.*\S)\s*$")
ANY_HEADING_RE = re.compile(r"^#{1,6}\s")

# legacy shapes gdoc.promote_headings turns into headings on the way up
BOLD_SECTION_RE = re.compile(r"^\*\*\d+\.\s*(?P<text>.+?)\*\*\s*$")
BOLD_BULLET_RE = re.compile(r"^[ \t]*[-*+][ \t]+\*\*(?P<text>.+?)\*\*[ \t]*$")

# the model's own restated title, which gdoc.to_gdoc_markdown drops on upload
RESTATED_TITLE_RE = re.compile(r"^#\s+Recording Summary\s*\n+(\*\*(?!\d+\.)[^\n]+\*\*)\s*$",
                               re.MULTILINE)

BULLET_RE = re.compile(r"^(?P<indent>[ \t]*)(?P<marker>[-*+])(?P<gap>[ \t]+)(?P<text>\S.*)$")

# Google Docs backslash-escapes Markdown punctuation on export ("會議結束\~")
ESCAPE_RE = re.compile(r"\\([!\"#$%&'()*+,\-./:;<=>?@\[\\\]^_`{|}~])")

DEFAULT_INDENT = 2

# frontmatter key holding the Google Docs file id this summary syncs with;
# gdoc.py never renders it, so it stays out of the uploaded document
DOC_ID_KEY = "gdoc_id"

# "**講者：** 張三" — the colon may sit inside or outside the bold run, and is
# required, so a bold-only legacy section title is not read as metadata
META_LINE_RE = re.compile(
    r"^\*\*\s*(?P<label>[^*：:]+?)\s*(?:[：:]\s*\*\*|\*\*\s*[：:])\s*(?P<value>.*?)\s*$"
)


def _dump_frontmatter(meta):
    return yaml.safe_dump(
        meta, allow_unicode=True, sort_keys=False, width=100000,
    ).strip()


def _strip_hard_break(line):
    """Drop the trailing hard-break markers Google Docs round-trips through."""
    return re.sub(r"[ \t]*\\?$", "", line.rstrip())


def parse_gdoc_header(exported):
    """Split the exported doc into (title, {key: value}, body)."""
    lines = exported.lstrip("﻿").split("\n")
    i = 0

    title = None
    while i < len(lines) and not lines[i].strip():
        i += 1
    if i < len(lines):
        m = re.match(r"^#\s+(.*\S)\s*$", lines[i])
        if m:
            title = m.group(1)
            i += 1

    # The metadata block is one paragraph of hard-broken lines, so blank lines
    # are only skipped ahead of it. A label the pipeline does not know keys the
    # field under its own name rather than ending the block.
    meta = {}
    while i < len(lines):
        line = _strip_hard_break(lines[i])
        if not line.strip():
            if meta:
                break
            i += 1
            continue
        m = META_LINE_RE.match(line)
        if not m:
            break
        label = m.group("label").strip()
        value = m.group("value")
        if value:
            meta[LABEL_TO_KEY.get(label, label)] = value
        i += 1

    return title, meta, "\n".join(lines[i:]).strip()


def merge_frontmatter(local_meta, title, gdoc_meta):
    """Rebuild the frontmatter from the document, which is the source of truth.

    Renaming a label in Google Docs renames the field, adding one adds a field,
    and dropping one drops it. Two things do not come from the document: the
    ``gdoc_id`` bookkeeping key, which is never rendered into it, and the exact
    YAML form of an unchanged value — a ``date:`` that loaded as a date object
    stays one rather than being churned into a quoted string.

    A document with no header block at all is treated as a failure to find the
    metadata rather than a request to delete all of it.
    """
    if title is None and not gdoc_meta:
        return dict(local_meta)

    def keep_local_type(key, value):
        if key in local_meta and str(local_meta[key]) == value:
            return local_meta[key]
        return value

    merged = {}
    if title is not None:
        merged["title"] = keep_local_type("title", title)
    elif "title" in local_meta:
        merged["title"] = local_meta["title"]

    for key, value in gdoc_meta.items():
        merged[key] = keep_local_type(key, value)

    if DOC_ID_KEY in local_meta:
        merged.setdefault(DOC_ID_KEY, local_meta[DOC_ID_KEY])
    return merged


def _bold_section_lines(local_body):
    """Map heading text back to the bold line the local file writes it as."""
    lines = {}
    for line in local_body.split("\n"):
        for pattern in (BOLD_SECTION_RE, BOLD_BULLET_RE):
            m = pattern.match(line)
            if m:
                lines[m.group("text").strip()] = (line, pattern is BOLD_BULLET_RE)
                break
    return lines


def demote_headings(body, local_body):
    """Undo gdoc.promote_headings for summaries that use bold section titles.

    Only headings the local file actually writes as bold are demoted, so files
    that already use real headings keep them.
    """
    bold = _bold_section_lines(local_body)
    if not bold:
        return body

    lines = body.split("\n")
    out = []
    i = 0
    while i < len(lines):
        m = HEADING_RE.match(lines[i])
        entry = bold.get(m.group("text")) if m else None
        if entry is None:
            out.append(lines[i])
            i += 1
            continue

        replacement, is_bullet = entry
        out.append(replacement)
        i += 1
        # A bold bullet sits directly above its detail points; the blank line
        # Google Docs puts under the heading would split the list.
        if is_bullet:
            j = i
            while j < len(lines) and not lines[j].strip():
                j += 1
            if j < len(lines) and BULLET_RE.match(lines[j]):
                i = j
    return "\n".join(out)


def _bullet_style(md):
    """Return the (marker, gap, indent_unit) a document writes its bullets with."""
    markers, gaps, indents = [], [], set()
    for line in md.split("\n"):
        m = BULLET_RE.match(line)
        if not m:
            continue
        markers.append(m.group("marker"))
        gaps.append(m.group("gap"))
        width = len(m.group("indent").expandtabs(4))
        if width:
            indents.add(width)
    marker = Counter(markers).most_common(1)[0][0] if markers else "-"
    gap = Counter(gaps).most_common(1)[0][0] if gaps else " "
    return marker, gap, min(indents) if indents else DEFAULT_INDENT


def _bullets(md, unit):
    """Every bullet in document order as (text, depth)."""
    found = []
    for line in md.split("\n"):
        m = BULLET_RE.match(line)
        if m:
            found.append((m.group("text").strip(),
                          len(m.group("indent").expandtabs(4)) // unit))
    return found


def _align_depths(local_bullets, doc_bullets, doc_has_indent):
    """Decide a depth for each exported bullet by lining the two lists up.

    Google Docs can come back with every bullet flattened to a single level, so
    the export's own indentation is often worthless. Diffing the bullet texts
    puts an edited bullet back at the depth its local counterpart had, instead
    of stranding it — and its children with it — at the top level.
    """
    matcher = difflib.SequenceMatcher(
        a=[text for text, _ in local_bullets],
        b=[text for text, _ in doc_bullets],
        autojunk=False,
    )
    depths = [None] * len(doc_bullets)
    for tag, i1, i2, j1, j2 in matcher.get_opcodes():
        if tag not in ("equal", "replace"):
            continue
        for offset in range(j2 - j1):
            if i1 + offset < i2:
                depths[j1 + offset] = local_bullets[i1 + offset][1]

    resolved, previous = [], 0
    for index, depth in enumerate(depths):
        if depth is None:
            # A bullet with no counterpart: trust the export when it still
            # carries indentation, otherwise make it a sibling of the one above.
            depth = doc_bullets[index][1] if doc_has_indent else previous
        resolved.append(depth)
        previous = depth
    return resolved


def restore_bullets(body, local_body):
    """Re-write exported bullets in the local file's marker and indent style.

    Google Docs re-markers every bullet and flattens the nesting, so an
    untouched list would otherwise show up as an edit on every line. Depths
    come from the local file via :func:`_align_depths`, clamped so a restored
    level can never skip its parent.
    """
    marker, gap, unit = _bullet_style(local_body)
    _, _, src_unit = _bullet_style(body)
    local_bullets = _bullets(local_body, unit)
    doc_bullets = _bullets(body, src_unit)
    depths = _align_depths(local_bullets, doc_bullets,
                           any(depth for _, depth in doc_bullets))

    out = []
    prev_depth = -1
    seen = 0
    for line in body.split("\n"):
        m = BULLET_RE.match(line)
        if not m:
            out.append(line)
            if line.strip():
                prev_depth = -1
            continue
        depth = max(0, min(depths[seen], prev_depth + 1))
        out.append(f"{' ' * (unit * depth)}{marker}{gap}{doc_bullets[seen][0]}")
        prev_depth = depth
        seen += 1
    return "\n".join(out)


def _blank_line_habits(md):
    """How the local file spaces its blocks.

    Returns (after a heading, between bullets, ahead of a list), each True when
    the file usually leaves a blank line there.
    """
    lines = md.split("\n")
    after_heading = [0, 0]      # [tight, spaced]
    between_bullets = [0, 0]
    before_list = [0, 0]
    for i, line in enumerate(lines[:-1]):
        if not line.strip():
            continue
        is_heading = bool(ANY_HEADING_RE.match(line))
        is_bullet = bool(BULLET_RE.match(line))

        j = i + 1
        while j < len(lines) and not lines[j].strip():
            j += 1
        if j >= len(lines):
            continue
        spaced = j > i + 1

        if is_heading:
            after_heading[spaced] += 1
        elif is_bullet:
            if BULLET_RE.match(lines[j]):
                between_bullets[spaced] += 1
        elif BULLET_RE.match(lines[j]):
            before_list[spaced] += 1
    return (after_heading[1] > after_heading[0],
            between_bullets[1] > between_bullets[0],
            before_list[1] > before_list[0])


def normalize_blank_lines(body, local_body):
    """Space blocks the way the local file does.

    Google Docs exports every block as its own paragraph, so it puts a blank
    line under each heading and between list groups. Left alone those show up
    as edits on a file the pipeline writes tightly.
    """
    spaced_headings, spaced_bullets, spaced_lists = _blank_line_habits(local_body)
    lines = body.split("\n")
    out = []
    i = 0
    while i < len(lines):
        line = lines[i]
        out.append(line)
        i += 1

        if not line.strip():
            continue
        is_heading = bool(ANY_HEADING_RE.match(line))
        is_bullet = bool(BULLET_RE.match(line))

        j = i
        while j < len(lines) and not lines[j].strip():
            j += 1
        if j == i or j >= len(lines):
            continue
        next_is_bullet = bool(BULLET_RE.match(lines[j]))

        if is_heading:
            keep_blank = spaced_headings
        elif is_bullet:
            keep_blank = spaced_bullets if next_is_bullet else True
        elif next_is_bullet:
            keep_blank = spaced_lists
        else:
            keep_blank = True
        if keep_blank:
            out.append("")
        i = j
    return "\n".join(out)


def from_gdoc_markdown(exported, local_md, doc_id=None):
    """Rebuild the Obsidian summary from a Google Docs export."""
    exported = ESCAPE_RE.sub(r"\1", exported)
    local_meta, local_body = split_frontmatter(local_md)
    title, gdoc_meta, body = parse_gdoc_header(exported)
    meta = merge_frontmatter(local_meta, title, gdoc_meta)
    if doc_id:
        meta[DOC_ID_KEY] = doc_id

    # Google Docs drops the italic generator line and leaves the bare rule
    # behind; put the local footer back so it never reads as an edit.
    footer = FOOTER_RE.search(local_body)
    if footer:
        body = TRAILING_RULE_RE.sub("", body)
    restated = RESTATED_TITLE_RE.search(local_body)
    if restated and not body.startswith(restated.group(1)):
        body = f"{restated.group(1)}\n\n{body}"
    body = demote_headings(body, local_body)
    body = restore_bullets(body, local_body)
    body = normalize_blank_lines(body, local_body)

    parts = []
    if meta:
        parts.append(f"---\n{_dump_frontmatter(meta)}\n---")
    parts.append("# Recording Summary")
    parts.append(body.strip())
    if footer:
        parts.append(f"---\n{footer.group(1)}")
    return "\n\n".join(parts).rstrip() + "\n"


def export_doc(doc_id):
    """Export a Google Doc as Markdown via the ``gws`` CLI."""
    params = json.dumps({"fileId": doc_id, "mimeType": "text/markdown"})
    workdir = tempfile.mkdtemp()
    try:
        # gws resolves file arguments relative to the working directory, so run
        # it inside a scratch dir and hand it a bare filename.
        subprocess.run(
            ["gws", "drive", "files", "export", "--params", params, "-o", "exported.md"],
            cwd=workdir, check=True,
        )
        with open(os.path.join(workdir, "exported.md"), encoding="utf-8") as f:
            return f.read()
    finally:
        shutil.rmtree(workdir, ignore_errors=True)


def _ask():
    return input("  Apply these changes to the local summary? [y/N] ").strip().lower() in ("y", "yes")


def sync(path, doc_id=None, from_file=None, assume_yes=False,
         exporter=export_doc, confirm=None, out=sys.stdout):
    """Pull the Google Doc back into ``path``. Returns a process exit code."""
    with open(path, encoding="utf-8") as f:
        local = f.read()

    meta, _ = split_frontmatter(local)
    resolved = doc_id or meta.get(DOC_ID_KEY)
    if not from_file and not resolved:
        print(f"No {DOC_ID_KEY} in {path}. Pass --doc-id <id> once and it will be "
              f"recorded in the frontmatter.", file=out)
        return 1

    if from_file:
        with open(from_file, encoding="utf-8") as f:
            exported = f.read()
    else:
        exported = exporter(resolved)

    updated = from_gdoc_markdown(exported, local, doc_id=doc_id)
    if updated == local:
        print(f"{path} is up to date — no changes in the Google Doc.", file=out)
        return 0

    diff = difflib.unified_diff(
        local.splitlines(), updated.splitlines(),
        fromfile=f"{path} (local)", tofile="Google Doc", lineterm="",
    )
    print("\n".join(diff), file=out)
    print(file=out)

    if not assume_yes and not (confirm or _ask)():
        print("Aborted — local file left unchanged.", file=out)
        return 0

    with open(path, "w", encoding="utf-8") as f:
        f.write(updated)
    print(f"Updated {path}", file=out)
    return 0


def main(argv=None):
    p = argparse.ArgumentParser(
        prog="python3 -m video_summary.gdoc_sync",
        description="Pull edits made in Google Docs back into the local summary.md",
    )
    p.add_argument("path", help="Local summary markdown file to update")
    p.add_argument("--doc-id", help=f"Google Docs file id (recorded as {DOC_ID_KEY} in the frontmatter)")
    p.add_argument("--from-file", metavar="MD",
                   help="Use an already-exported markdown file instead of calling gws")
    p.add_argument("-y", "--yes", action="store_true", help="Apply without confirming")
    args = p.parse_args(argv)

    return sync(args.path, doc_id=args.doc_id, from_file=args.from_file, assume_yes=args.yes)


if __name__ == "__main__":
    sys.exit(main())
