"""Tests for the Google Docs -> Obsidian summary reverse conversion."""

import difflib
import io
import os
import re
import shutil
import sys
import tempfile
import unittest

import yaml

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from video_summary import gdoc, gdoc_sync
from video_summary.gdoc_sync import from_gdoc_markdown


LOCAL = """---
title: 高中校舍願景論壇
speaker: 張三
date: 2026-08-01
gdoc_id: 1AbC_dEfGh
---

# Recording Summary

## 概述 Overview

這場論壇討論了校舍改建。

---
*Generated by video_summary using google/gemini-2.5-pro*
"""

EXPORTED = """# 高中校舍願景論壇

**講者：** 張三
**日期：** 2026-08-01

## 概述 Overview

這場論壇討論了校舍改建。

---
"""


class MetadataBlock(unittest.TestCase):
    def test_metadata_block_becomes_frontmatter(self):
        out = from_gdoc_markdown(EXPORTED, LOCAL)
        self.assertTrue(out.startswith("---\n"))
        self.assertIn("title: 高中校舍願景論壇\n", out)
        self.assertIn("speaker: 張三\n", out)
        self.assertIn("date: 2026-08-01\n", out)
        self.assertNotIn("**講者：**", out)

    def test_recording_summary_heading_restored(self):
        out = from_gdoc_markdown(EXPORTED, LOCAL)
        self.assertIn("\n# Recording Summary\n", out)
        self.assertNotIn("# 高中校舍願景論壇", out)


class Footer(unittest.TestCase):
    def test_footer_restored_from_local(self):
        out = from_gdoc_markdown(EXPORTED, LOCAL)
        self.assertTrue(
            out.endswith("---\n*Generated by video_summary using google/gemini-2.5-pro*\n"),
            out[-120:],
        )

    def test_bare_rule_left_by_google_docs_is_not_duplicated(self):
        out = from_gdoc_markdown(EXPORTED, LOCAL)
        self.assertEqual(out.count("\n---\n"), 2)  # frontmatter close + footer rule


class LocalOnlyFields(unittest.TestCase):
    def test_gdoc_id_survives_the_round_trip(self):
        out = from_gdoc_markdown(EXPORTED, LOCAL)
        self.assertIn("gdoc_id: 1AbC_dEfGh\n", out)


class UneditedDoc(unittest.TestCase):
    def test_unedited_doc_reproduces_the_local_file_byte_for_byte(self):
        self.assertEqual(from_gdoc_markdown(EXPORTED, LOCAL), LOCAL)


if __name__ == "__main__":
    unittest.main()


LOCAL_NESTED = """---
title: 高中校舍願景論壇
gdoc_id: 1AbC_dEfGh
---

# Recording Summary

## 內容詳述 Detailed Breakdown

### 論壇背景

- 起因是校舍老舊
  - 民國 60 年興建
    - 已超過使用年限
- 家長會提出訴求

---
*Generated by video_summary using google/gemini-2.5-pro*
"""

# Google Docs re-markers every bullet as "*   " on a 4-space grid and flattens
# anything nested deeper than two levels.
EXPORTED_NESTED = """# 高中校舍願景論壇

## 內容詳述 Detailed Breakdown

### 論壇背景

*   起因是校舍老舊
    *   民國 60 年興建
    *   已超過使用年限
*   家長會提出訴求

---
"""


class Bullets(unittest.TestCase):
    def test_unedited_nested_list_reproduces_the_local_file(self):
        self.assertEqual(from_gdoc_markdown(EXPORTED_NESTED, LOCAL_NESTED), LOCAL_NESTED)

    def test_edited_bullet_keeps_the_new_text_at_local_marker_style(self):
        exported = EXPORTED_NESTED.replace("*   家長會提出訴求", "*   家長會提出改建訴求")
        out = from_gdoc_markdown(exported, LOCAL_NESTED)
        self.assertIn("\n- 家長會提出改建訴求\n", out)
        self.assertNotIn("家長會提出訴求\n", out)

    def test_bullet_added_in_the_doc_is_kept_at_its_exported_depth(self):
        exported = EXPORTED_NESTED.replace(
            "    *   民國 60 年興建", "    *   民國 60 年興建\n    *   工程分三期"
        )
        out = from_gdoc_markdown(exported, LOCAL_NESTED)
        self.assertIn("\n  - 工程分三期\n", out)

    def test_restored_depth_never_skips_a_level(self):
        # The grandparent was deleted in the doc; "已超過使用年限" must not be
        # re-indented to depth 2 with nothing above it.
        exported = EXPORTED_NESTED.replace("    *   民國 60 年興建\n", "")
        out = from_gdoc_markdown(exported, LOCAL_NESTED)
        self.assertIn("\n  - 已超過使用年限\n", out)


# Summaries written before the prompt asked for real headings put each theme in
# a bold-only bullet; gdoc.py promotes those to "###" on the way up.
LOCAL_LEGACY = """---
title: 高中校舍願景論壇
gdoc_id: 1AbC_dEfGh
---

# Recording Summary

**1. 概述**

這場論壇討論了校舍改建。

**3. 內容詳述**

*   **論壇背景**
    *   起因是校舍老舊

---
*Generated by video_summary using google/gemini-2.5-pro*
"""

EXPORTED_LEGACY = """# 高中校舍願景論壇

## 概述

這場論壇討論了校舍改建。

## 內容詳述

### 論壇背景

*   起因是校舍老舊

---
"""


class LegacyBoldSections(unittest.TestCase):
    def test_headings_are_demoted_back_to_the_local_bold_form(self):
        self.assertEqual(from_gdoc_markdown(EXPORTED_LEGACY, LOCAL_LEGACY), LOCAL_LEGACY)

    def test_modern_heading_files_keep_their_headings(self):
        out = from_gdoc_markdown(EXPORTED_NESTED, LOCAL_NESTED)
        self.assertIn("\n### 論壇背景\n", out)


class DocIdRecording(unittest.TestCase):
    def test_doc_id_is_written_into_frontmatter_when_missing(self):
        local = LOCAL.replace("gdoc_id: 1AbC_dEfGh\n", "")
        out = from_gdoc_markdown(EXPORTED, local, doc_id="1AbC_dEfGh")
        self.assertIn("gdoc_id: 1AbC_dEfGh\n", out)

    def test_existing_doc_id_is_not_duplicated(self):
        out = from_gdoc_markdown(EXPORTED, LOCAL, doc_id="1AbC_dEfGh")
        self.assertEqual(out.count("gdoc_id"), 1)
        self.assertEqual(out, LOCAL)


class Sync(unittest.TestCase):
    def setUp(self):
        self.dir = tempfile.mkdtemp()
        self.path = os.path.join(self.dir, "summary.md")
        with open(self.path, "w", encoding="utf-8") as f:
            f.write(LOCAL)
        self.out = io.StringIO()
        self.exported_calls = []

    def tearDown(self):
        shutil.rmtree(self.dir)

    def _exporter(self, text):
        def export(doc_id):
            self.exported_calls.append(doc_id)
            return text
        return export

    def _read(self):
        with open(self.path, encoding="utf-8") as f:
            return f.read()

    def test_confirmed_edit_is_written_to_the_local_file(self):
        edited = EXPORTED.replace("這場論壇討論了校舍改建。", "這場論壇討論了校舍改建與經費。")
        rc = gdoc_sync.sync(self.path, exporter=self._exporter(edited),
                            confirm=lambda: True, out=self.out)
        self.assertEqual(rc, 0)
        self.assertIn("校舍改建與經費。", self._read())

    def test_declined_edit_leaves_the_file_untouched(self):
        edited = EXPORTED.replace("這場論壇討論了校舍改建。", "這場論壇討論了校舍改建與經費。")
        rc = gdoc_sync.sync(self.path, exporter=self._exporter(edited),
                            confirm=lambda: False, out=self.out)
        self.assertEqual(rc, 0)
        self.assertEqual(self._read(), LOCAL)

    def test_identical_doc_reports_no_changes_without_asking(self):
        def refuse():
            raise AssertionError("should not prompt when there is nothing to apply")
        rc = gdoc_sync.sync(self.path, exporter=self._exporter(EXPORTED),
                            confirm=refuse, out=self.out)
        self.assertEqual(rc, 0)
        self.assertEqual(self._read(), LOCAL)
        self.assertIn("no changes", self.out.getvalue().lower())

    def test_doc_id_comes_from_the_frontmatter(self):
        gdoc_sync.sync(self.path, exporter=self._exporter(EXPORTED),
                       confirm=lambda: True, out=self.out)
        self.assertEqual(self.exported_calls, ["1AbC_dEfGh"])

    def test_explicit_doc_id_is_recorded_for_next_time(self):
        with open(self.path, "w", encoding="utf-8") as f:
            f.write(LOCAL.replace("gdoc_id: 1AbC_dEfGh\n", ""))
        rc = gdoc_sync.sync(self.path, doc_id="9ZyX", exporter=self._exporter(EXPORTED),
                            confirm=lambda: True, out=self.out)
        self.assertEqual(rc, 0)
        self.assertEqual(self.exported_calls, ["9ZyX"])
        self.assertIn("gdoc_id: 9ZyX", self._read())

    def test_missing_doc_id_is_an_error(self):
        with open(self.path, "w", encoding="utf-8") as f:
            f.write(LOCAL.replace("gdoc_id: 1AbC_dEfGh\n", ""))
        rc = gdoc_sync.sync(self.path, exporter=self._exporter(EXPORTED),
                            confirm=lambda: True, out=self.out)
        self.assertEqual(rc, 1)
        self.assertIn("--doc-id", self.out.getvalue())

    def test_from_file_skips_the_export(self):
        src = os.path.join(self.dir, "exported.md")
        with open(src, "w", encoding="utf-8") as f:
            f.write(EXPORTED.replace("校舍改建。", "校舍改建與經費。"))
        rc = gdoc_sync.sync(self.path, from_file=src, exporter=self._exporter(EXPORTED),
                            confirm=lambda: True, out=self.out)
        self.assertEqual(rc, 0)
        self.assertEqual(self.exported_calls, [])
        self.assertIn("校舍改建與經費。", self._read())

    def test_assume_yes_writes_without_prompting(self):
        edited = EXPORTED.replace("校舍改建。", "校舍改建與經費。")
        def refuse():
            raise AssertionError("should not prompt with assume_yes")
        rc = gdoc_sync.sync(self.path, exporter=self._exporter(edited),
                            confirm=refuse, assume_yes=True, out=self.out)
        self.assertEqual(rc, 0)
        self.assertIn("校舍改建與經費。", self._read())

    def test_diff_is_shown_before_asking(self):
        edited = EXPORTED.replace("校舍改建。", "校舍改建與經費。")
        gdoc_sync.sync(self.path, exporter=self._exporter(edited),
                       confirm=lambda: True, out=self.out)
        printed = self.out.getvalue()
        self.assertIn("-這場論壇討論了校舍改建。", printed)
        self.assertIn("+這場論壇討論了校舍改建與經費。", printed)


def simulate_google_docs(gdoc_md):
    """Model what Google Docs gives back after importing gdoc.py's output.

    Checked against a real round trip (a 128-line summary through Docs and
    back): every bullet comes back flattened to a single level and re-markered
    as "- ", each heading gains a blank line under it, list groups are split by
    blank lines, and the italic generator footer is swallowed, leaving the bare
    rule behind.
    """
    out = []
    for line in gdoc_md.split("\n"):
        if re.match(r"^\*Generated by .*\*\s*$", line):
            continue
        m = re.match(r"^[ \t]*[-*+][ \t]+(?P<text>\S.*)$", line)
        if m:
            if out and not out[-1].strip() is False and re.match(r"^#{1,6}\s", out[-1]):
                out.append("")
            out.append(f"- {m.group('text')}")
            continue
        if re.match(r"^#{1,6}\s", line):
            out.append(line)
            out.append("")
            continue
        if out and re.match(r"^- ", out[-1]) and line.strip() and not line.startswith("#"):
            out.append("")
        out.append(line)
    return re.sub(r"\n{3,}", "\n\n", "\n".join(out)).rstrip() + "\n"


LOCAL_LEGACY_TITLED = LOCAL_LEGACY.replace(
    "# Recording Summary\n", "# Recording Summary\n\n**高中校舍願景論壇摘要**\n")


class ForwardConverterContract(unittest.TestCase):
    """gdoc_sync relies on gdoc.py keeping gdoc_id out of the uploaded doc."""

    def test_gdoc_id_is_never_rendered_into_the_google_doc(self):
        uploaded = gdoc.to_gdoc_markdown(LOCAL)
        self.assertNotIn("gdoc_id", uploaded)
        self.assertNotIn("1AbC_dEfGh", uploaded)

    def test_numbered_section_is_not_mistaken_for_a_repeated_title(self):
        uploaded = gdoc.to_gdoc_markdown(LOCAL_LEGACY)
        self.assertIn("## 概述", uploaded)

    def test_repeated_bold_title_line_is_still_dropped(self):
        titled = LOCAL_LEGACY.replace(
            "# Recording Summary\n", "# Recording Summary\n\n**高中校舍願景論壇摘要**")
        uploaded = gdoc.to_gdoc_markdown(titled)
        self.assertNotIn("**高中校舍願景論壇摘要**", uploaded)


class FullRoundTrip(unittest.TestCase):
    def test_untouched_document_comes_back_unchanged(self):
        fixtures = (("simple", LOCAL), ("nested", LOCAL_NESTED), ("tight", LOCAL_TIGHT),
                    ("legacy", LOCAL_LEGACY), ("legacy-titled", LOCAL_LEGACY_TITLED))
        for name, local in fixtures:
            with self.subTest(fixture=name):
                exported = simulate_google_docs(gdoc.to_gdoc_markdown(local))
                self.assertEqual(from_gdoc_markdown(exported, local), local)

    def test_only_the_real_edit_shows_up_in_the_diff(self):
        exported = simulate_google_docs(gdoc.to_gdoc_markdown(LOCAL_NESTED))
        exported = exported.replace("民國 60 年興建", "民國 62 年興建")
        out = from_gdoc_markdown(exported, LOCAL_NESTED)
        diff = [l for l in difflib.unified_diff(
            LOCAL_NESTED.splitlines(), out.splitlines(), lineterm="", n=0)
            if l[:1] in "+-" and not l.startswith(("---", "+++"))]
        self.assertEqual(diff, ["-  - 民國 60 年興建", "+  - 民國 62 年興建"])


# The real pipeline writes headings and list items with no blank line between
# them; Google Docs puts one after every heading and between list groups.
LOCAL_TIGHT = """---
title: 班親會
gdoc_id: 1AbC_dEfGh
---

# Recording Summary

## 概述 Overview
本次會議由導師主持。

## 內容詳述 Detailed Breakdown
### 暑期準備
會議中完成以下分組：
- **生活適應：**
  - 熟悉環境。
  - 練習自理。
- **開學初期：**
  - 送到教室門口。

---
*Generated by video_summary using google/gemini-2.5-pro*
"""

EXPORTED_LOOSE = """# 班親會

## 概述

本次會議由導師主持。

## 內容詳述

### 暑期準備

會議中完成以下分組：

### 生活適應：

- 熟悉環境。
- 練習自理。

### 開學初期：

- 送到教室門口。

---
"""


class BlankLines(unittest.TestCase):
    def test_blank_line_after_heading_is_dropped_when_local_has_none(self):
        out = from_gdoc_markdown(EXPORTED_LOOSE, LOCAL_TIGHT)
        self.assertIn("## 概述\n本次會議由導師主持。", out)
        self.assertIn("## 內容詳述\n### 暑期準備\n", out)

    def test_blank_line_between_list_groups_is_dropped(self):
        out = from_gdoc_markdown(EXPORTED_LOOSE, LOCAL_TIGHT)
        self.assertIn("  - 練習自理。\n- **開學初期：**\n", out)

    def test_blank_line_after_heading_is_kept_when_local_has_one(self):
        out = from_gdoc_markdown(EXPORTED, LOCAL)
        self.assertIn("## 概述 Overview\n\n這場論壇", out)

    def test_blank_line_between_a_paragraph_and_its_list_is_dropped(self):
        out = from_gdoc_markdown(EXPORTED_LOOSE, LOCAL_TIGHT)
        self.assertIn("會議中完成以下分組：\n- **生活適應：**", out)

    def test_blank_line_before_a_heading_is_preserved(self):
        out = from_gdoc_markdown(EXPORTED_LOOSE, LOCAL_TIGHT)
        self.assertIn("本次會議由導師主持。\n\n## 內容詳述", out)


class ForwardConverterHeadings(unittest.TestCase):
    def test_bold_sub_bullets_survive_when_the_file_already_uses_headings(self):
        uploaded = gdoc.to_gdoc_markdown(LOCAL_TIGHT)
        self.assertIn("- **生活適應：**", uploaded)
        self.assertNotIn("### 生活適應：", uploaded)

    def test_theme_headings_are_untouched(self):
        uploaded = gdoc.to_gdoc_markdown(LOCAL_TIGHT)
        self.assertIn("### 暑期準備", uploaded)

    def test_legacy_bold_themes_are_still_promoted(self):
        uploaded = gdoc.to_gdoc_markdown(LOCAL_LEGACY)
        self.assertIn("### 論壇背景", uploaded)


class ForwardConverterMetadata(unittest.TestCase):
    def test_non_standard_frontmatter_keys_are_rendered(self):
        local = LOCAL.replace("gdoc_id:", "紀錄: 昀希爸爸\ngdoc_id:")
        uploaded = gdoc.to_gdoc_markdown(local)
        self.assertIn("**紀錄：** 昀希爸爸", uploaded)
        self.assertNotIn("gdoc_id", uploaded)

    def test_standard_keys_keep_their_chinese_labels(self):
        uploaded = gdoc.to_gdoc_markdown(LOCAL)
        self.assertIn("**講者：** 張三", uploaded)


# The doc's metadata block is the source of truth: a label renamed in Google
# Docs renames the field, a new label adds one, a removed label removes one.
EXPORTED_RENAMED = """# 高中校舍願景論壇

**導師：** 張三
**日期：** 2026-08-01
**紀錄：** 昀希爸爸

## 概述 Overview

這場論壇討論了校舍改建。

---
"""


class MetadataIsAuthoritative(unittest.TestCase):
    def setUp(self):
        self.out = from_gdoc_markdown(EXPORTED_RENAMED, LOCAL)
        self.meta = yaml.safe_load(self.out.split("---\n")[1])

    def test_unknown_label_becomes_a_frontmatter_field(self):
        self.assertEqual(self.meta["紀錄"], "昀希爸爸")

    def test_renamed_label_replaces_the_old_field(self):
        self.assertEqual(self.meta["導師"], "張三")
        self.assertNotIn("speaker", self.meta)

    def test_field_dropped_in_the_doc_is_dropped_locally(self):
        local = LOCAL.replace("speaker: 張三\n", "speaker: 張三\naudience: 家長\n")
        out = from_gdoc_markdown(EXPORTED_RENAMED, local)
        self.assertNotIn("audience", yaml.safe_load(out.split("---\n")[1]))

    def test_document_with_no_header_block_keeps_the_local_frontmatter(self):
        headless = "## 概述 Overview\n\n這場論壇討論了校舍改建。\n\n---\n"
        out = from_gdoc_markdown(headless, LOCAL)
        self.assertEqual(yaml.safe_load(out.split("---\n")[1]),
                         yaml.safe_load(LOCAL.split("---\n")[1]))

    def test_field_order_follows_the_document(self):
        self.assertEqual(list(self.meta), ["title", "導師", "date", "紀錄", "gdoc_id"])

    def test_gdoc_id_still_survives(self):
        self.assertEqual(self.meta["gdoc_id"], "1AbC_dEfGh")

    def test_unchanged_value_keeps_its_local_yaml_type(self):
        self.assertIn("date: 2026-08-01\n", self.out)


class MarkdownEscapes(unittest.TestCase):
    def test_escapes_google_docs_adds_are_removed(self):
        exported = EXPORTED.replace("這場論壇討論了校舍改建。", "會議結束\\~ 經費 3\\.5 萬")
        out = from_gdoc_markdown(exported, LOCAL)
        self.assertIn("會議結束~ 經費 3.5 萬", out)

    def test_escaped_bullet_text_still_matches_its_local_counterpart(self):
        exported = EXPORTED_NESTED.replace("家長會提出訴求", "家長會提出訴求\\!")
        out = from_gdoc_markdown(exported, LOCAL_NESTED)
        self.assertIn("\n- 家長會提出訴求!\n", out)
        self.assertNotIn("\\", out)
