"""Tests for the Google Docs -> Obsidian summary reverse conversion."""

import difflib
import io
import os
import re
import shutil
import subprocess
import sys
import tempfile
import unittest
from unittest import mock

import yaml

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from video_summary import cli, gdoc, gdoc_sync
from video_summary.gdoc_sync import from_gdoc_markdown


LOCAL = """---
title: 高中校舍願景論壇
speaker: 張三
date: 2026-08-01
gdoc_id: 1AbC_dEfGh
---

# Recording Summary

## 概述 Overview

這場論壇討論了校舍改建。

---
*Generated by video_summary using google/gemini-2.5-pro*
"""

EXPORTED = """# 高中校舍願景論壇

**講者：** 張三
**日期：** 2026-08-01

## 概述 Overview

這場論壇討論了校舍改建。

---
"""


class MetadataBlock(unittest.TestCase):
    def test_metadata_block_becomes_frontmatter(self):
        out = from_gdoc_markdown(EXPORTED, LOCAL)
        self.assertTrue(out.startswith("---\n"))
        self.assertIn("title: 高中校舍願景論壇\n", out)
        self.assertIn("speaker: 張三\n", out)
        self.assertIn("date: 2026-08-01\n", out)
        self.assertNotIn("**講者：**", out)

    def test_recording_summary_heading_restored(self):
        out = from_gdoc_markdown(EXPORTED, LOCAL)
        self.assertIn("\n# Recording Summary\n", out)
        self.assertNotIn("# 高中校舍願景論壇", out)


class Footer(unittest.TestCase):
    def test_footer_restored_from_local(self):
        out = from_gdoc_markdown(EXPORTED, LOCAL)
        self.assertTrue(
            out.endswith("---\n*Generated by video_summary using google/gemini-2.5-pro*\n"),
            out[-120:],
        )

    def test_bare_rule_left_by_google_docs_is_not_duplicated(self):
        out = from_gdoc_markdown(EXPORTED, LOCAL)
        self.assertEqual(out.count("\n---\n"), 2)  # frontmatter close + footer rule


class LocalOnlyFields(unittest.TestCase):
    def test_gdoc_id_survives_the_round_trip(self):
        out = from_gdoc_markdown(EXPORTED, LOCAL)
        self.assertIn("gdoc_id: 1AbC_dEfGh\n", out)


class UneditedDoc(unittest.TestCase):
    def test_unedited_doc_reproduces_the_local_file_byte_for_byte(self):
        self.assertEqual(from_gdoc_markdown(EXPORTED, LOCAL), LOCAL)



LOCAL_NESTED = """---
title: 高中校舍願景論壇
gdoc_id: 1AbC_dEfGh
---

# Recording Summary

## 內容詳述 Detailed Breakdown

### 論壇背景

- 起因是校舍老舊
  - 民國 60 年興建
    - 已超過使用年限
- 家長會提出訴求

---
*Generated by video_summary using google/gemini-2.5-pro*
"""

# Google Docs re-markers every bullet as "*   " on a 4-space grid and flattens
# anything nested deeper than two levels.
EXPORTED_NESTED = """# 高中校舍願景論壇

## 內容詳述 Detailed Breakdown

### 論壇背景

*   起因是校舍老舊
    *   民國 60 年興建
    *   已超過使用年限
*   家長會提出訴求

---
"""


class Bullets(unittest.TestCase):
    def test_unedited_nested_list_reproduces_the_local_file(self):
        self.assertEqual(from_gdoc_markdown(EXPORTED_NESTED, LOCAL_NESTED), LOCAL_NESTED)

    def test_edited_bullet_keeps_the_new_text_at_local_marker_style(self):
        exported = EXPORTED_NESTED.replace("*   家長會提出訴求", "*   家長會提出改建訴求")
        out = from_gdoc_markdown(exported, LOCAL_NESTED)
        self.assertIn("\n- 家長會提出改建訴求\n", out)
        self.assertNotIn("家長會提出訴求\n", out)

    def test_bullet_added_in_the_doc_is_kept_at_its_exported_depth(self):
        exported = EXPORTED_NESTED.replace(
            "    *   民國 60 年興建", "    *   民國 60 年興建\n    *   工程分三期"
        )
        out = from_gdoc_markdown(exported, LOCAL_NESTED)
        self.assertIn("\n  - 工程分三期\n", out)

    def test_restored_depth_never_skips_a_level(self):
        # The grandparent was deleted in the doc; "已超過使用年限" must not be
        # re-indented to depth 2 with nothing above it.
        exported = EXPORTED_NESTED.replace("    *   民國 60 年興建\n", "")
        out = from_gdoc_markdown(exported, LOCAL_NESTED)
        self.assertIn("\n  - 已超過使用年限\n", out)


# Summaries written before the prompt asked for real headings put each theme in
# a bold-only bullet; gdoc.py promotes those to "###" on the way up.
LOCAL_LEGACY = """---
title: 高中校舍願景論壇
gdoc_id: 1AbC_dEfGh
---

# Recording Summary

**1. 概述**

這場論壇討論了校舍改建。

**3. 內容詳述**

*   **論壇背景**
    *   起因是校舍老舊

---
*Generated by video_summary using google/gemini-2.5-pro*
"""

EXPORTED_LEGACY = """# 高中校舍願景論壇

## 概述

這場論壇討論了校舍改建。

## 內容詳述

### 論壇背景

*   起因是校舍老舊

---
"""


class LegacyBoldSections(unittest.TestCase):
    def test_headings_are_demoted_back_to_the_local_bold_form(self):
        self.assertEqual(from_gdoc_markdown(EXPORTED_LEGACY, LOCAL_LEGACY), LOCAL_LEGACY)

    def test_modern_heading_files_keep_their_headings(self):
        out = from_gdoc_markdown(EXPORTED_NESTED, LOCAL_NESTED)
        self.assertIn("\n### 論壇背景\n", out)


class DocIdRecording(unittest.TestCase):
    def test_doc_id_is_written_into_frontmatter_when_missing(self):
        local = LOCAL.replace("gdoc_id: 1AbC_dEfGh\n", "")
        out = from_gdoc_markdown(EXPORTED, local, doc_id="1AbC_dEfGh")
        self.assertIn("gdoc_id: 1AbC_dEfGh\n", out)

    def test_existing_doc_id_is_not_duplicated(self):
        out = from_gdoc_markdown(EXPORTED, LOCAL, doc_id="1AbC_dEfGh")
        self.assertEqual(out.count("gdoc_id"), 1)
        self.assertEqual(out, LOCAL)


class Sync(unittest.TestCase):
    def setUp(self):
        self.dir = tempfile.mkdtemp()
        self.path = os.path.join(self.dir, "summary.md")
        with open(self.path, "w", encoding="utf-8") as f:
            f.write(LOCAL)
        self.out = io.StringIO()
        self.exported_calls = []

    def tearDown(self):
        shutil.rmtree(self.dir)

    def _exporter(self, text):
        def export(doc_id):
            self.exported_calls.append(doc_id)
            return text
        return export

    def _read(self):
        with open(self.path, encoding="utf-8") as f:
            return f.read()

    def test_confirmed_edit_is_written_to_the_local_file(self):
        edited = EXPORTED.replace("這場論壇討論了校舍改建。", "這場論壇討論了校舍改建與經費。")
        rc = gdoc_sync.sync(self.path, exporter=self._exporter(edited),
                            confirm=lambda: True, out=self.out)
        self.assertEqual(rc, 0)
        self.assertIn("校舍改建與經費。", self._read())

    def test_declined_edit_leaves_the_file_untouched(self):
        edited = EXPORTED.replace("這場論壇討論了校舍改建。", "這場論壇討論了校舍改建與經費。")
        rc = gdoc_sync.sync(self.path, exporter=self._exporter(edited),
                            confirm=lambda: False, out=self.out)
        self.assertEqual(rc, 0)
        self.assertEqual(self._read(), LOCAL)

    def test_identical_doc_reports_no_changes_without_asking(self):
        def refuse():
            raise AssertionError("should not prompt when there is nothing to apply")
        rc = gdoc_sync.sync(self.path, exporter=self._exporter(EXPORTED),
                            confirm=refuse, out=self.out)
        self.assertEqual(rc, 0)
        self.assertEqual(self._read(), LOCAL)
        self.assertIn("no changes", self.out.getvalue().lower())

    def test_doc_id_comes_from_the_frontmatter(self):
        gdoc_sync.sync(self.path, exporter=self._exporter(EXPORTED),
                       confirm=lambda: True, out=self.out)
        self.assertEqual(self.exported_calls, ["1AbC_dEfGh"])

    def test_explicit_doc_id_is_recorded_for_next_time(self):
        with open(self.path, "w", encoding="utf-8") as f:
            f.write(LOCAL.replace("gdoc_id: 1AbC_dEfGh\n", ""))
        rc = gdoc_sync.sync(self.path, doc_id="9ZyX", exporter=self._exporter(EXPORTED),
                            confirm=lambda: True, out=self.out)
        self.assertEqual(rc, 0)
        self.assertEqual(self.exported_calls, ["9ZyX"])
        self.assertIn("gdoc_id: 9ZyX", self._read())

    def test_missing_doc_id_is_an_error(self):
        with open(self.path, "w", encoding="utf-8") as f:
            f.write(LOCAL.replace("gdoc_id: 1AbC_dEfGh\n", ""))
        rc = gdoc_sync.sync(self.path, exporter=self._exporter(EXPORTED),
                            confirm=lambda: True, out=self.out)
        self.assertEqual(rc, 1)
        self.assertIn("--doc-id", self.out.getvalue())

    def test_from_file_skips_the_export(self):
        src = os.path.join(self.dir, "exported.md")
        with open(src, "w", encoding="utf-8") as f:
            f.write(EXPORTED.replace("校舍改建。", "校舍改建與經費。"))
        rc = gdoc_sync.sync(self.path, from_file=src, exporter=self._exporter(EXPORTED),
                            confirm=lambda: True, out=self.out)
        self.assertEqual(rc, 0)
        self.assertEqual(self.exported_calls, [])
        self.assertIn("校舍改建與經費。", self._read())

    def test_assume_yes_writes_without_prompting(self):
        edited = EXPORTED.replace("校舍改建。", "校舍改建與經費。")
        def refuse():
            raise AssertionError("should not prompt with assume_yes")
        rc = gdoc_sync.sync(self.path, exporter=self._exporter(edited),
                            confirm=refuse, assume_yes=True, out=self.out)
        self.assertEqual(rc, 0)
        self.assertIn("校舍改建與經費。", self._read())

    def test_diff_is_shown_before_asking(self):
        edited = EXPORTED.replace("校舍改建。", "校舍改建與經費。")
        gdoc_sync.sync(self.path, exporter=self._exporter(edited),
                       confirm=lambda: True, out=self.out)
        printed = self.out.getvalue()
        self.assertIn("-這場論壇討論了校舍改建。", printed)
        self.assertIn("+這場論壇討論了校舍改建與經費。", printed)


def simulate_google_docs(gdoc_md):
    """Model what Google Docs gives back after importing gdoc.py's output.

    Checked against a real round trip (a 128-line summary through Docs and
    back): every bullet comes back flattened to a single level and re-markered
    as "- ", each heading gains a blank line under it, list groups are split by
    blank lines, and the italic generator footer is swallowed, leaving the bare
    rule behind.
    """
    out = []
    for line in gdoc_md.split("\n"):
        if re.match(r"^\*Generated by .*\*\s*$", line):
            continue
        m = re.match(r"^[ \t]*[-*+][ \t]+(?P<text>\S.*)$", line)
        if m:
            if out and re.match(r"^#{1,6}\s", out[-1]):
                out.append("")
            out.append(f"- {m.group('text')}")
            continue
        if re.match(r"^#{1,6}\s", line):
            out.append(line)
            out.append("")
            continue
        if out and re.match(r"^- ", out[-1]) and line.strip() and not line.startswith("#"):
            out.append("")
        out.append(line)
    return re.sub(r"\n{3,}", "\n\n", "\n".join(out)).rstrip() + "\n"


LOCAL_LEGACY_TITLED = LOCAL_LEGACY.replace(
    "# Recording Summary\n", "# Recording Summary\n\n**高中校舍願景論壇摘要**\n")


class ForwardConverterContract(unittest.TestCase):
    """gdoc_sync relies on gdoc.py keeping gdoc_id out of the uploaded doc."""

    def test_gdoc_id_is_never_rendered_into_the_google_doc(self):
        uploaded = gdoc.to_gdoc_markdown(LOCAL)
        self.assertNotIn("gdoc_id", uploaded)
        self.assertNotIn("1AbC_dEfGh", uploaded)

    def test_numbered_section_is_not_mistaken_for_a_repeated_title(self):
        uploaded = gdoc.to_gdoc_markdown(LOCAL_LEGACY)
        self.assertIn("## 概述", uploaded)

    def test_repeated_bold_title_line_is_still_dropped(self):
        titled = LOCAL_LEGACY.replace(
            "# Recording Summary\n", "# Recording Summary\n\n**高中校舍願景論壇摘要**")
        uploaded = gdoc.to_gdoc_markdown(titled)
        self.assertNotIn("**高中校舍願景論壇摘要**", uploaded)


class FullRoundTrip(unittest.TestCase):
    def test_untouched_document_comes_back_unchanged(self):
        fixtures = (("simple", LOCAL), ("nested", LOCAL_NESTED), ("tight", LOCAL_TIGHT),
                    ("legacy", LOCAL_LEGACY), ("legacy-titled", LOCAL_LEGACY_TITLED))
        for name, local in fixtures:
            with self.subTest(fixture=name):
                exported = simulate_google_docs(gdoc.to_gdoc_markdown(local))
                self.assertEqual(from_gdoc_markdown(exported, local), local)

    def test_only_the_real_edit_shows_up_in_the_diff(self):
        exported = simulate_google_docs(gdoc.to_gdoc_markdown(LOCAL_NESTED))
        exported = exported.replace("民國 60 年興建", "民國 62 年興建")
        out = from_gdoc_markdown(exported, LOCAL_NESTED)
        diff = [l for l in difflib.unified_diff(
            LOCAL_NESTED.splitlines(), out.splitlines(), lineterm="", n=0)
            if l[:1] in "+-" and not l.startswith(("---", "+++"))]
        self.assertEqual(diff, ["-  - 民國 60 年興建", "+  - 民國 62 年興建"])


# The real pipeline writes headings and list items with no blank line between
# them; Google Docs puts one after every heading and between list groups.
LOCAL_TIGHT = """---
title: 班親會
gdoc_id: 1AbC_dEfGh
---

# Recording Summary

## 概述 Overview
本次會議由導師主持。

## 內容詳述 Detailed Breakdown
### 暑期準備
會議中完成以下分組：
- **生活適應：**
  - 熟悉環境。
  - 練習自理。
- **開學初期：**
  - 送到教室門口。

---
*Generated by video_summary using google/gemini-2.5-pro*
"""

EXPORTED_LOOSE = """# 班親會

## 概述

本次會議由導師主持。

## 內容詳述

### 暑期準備

會議中完成以下分組：

### 生活適應：

- 熟悉環境。
- 練習自理。

### 開學初期：

- 送到教室門口。

---
"""


class BlankLines(unittest.TestCase):
    def test_blank_line_after_heading_is_dropped_when_local_has_none(self):
        out = from_gdoc_markdown(EXPORTED_LOOSE, LOCAL_TIGHT)
        self.assertIn("## 概述\n本次會議由導師主持。", out)
        self.assertIn("## 內容詳述\n### 暑期準備\n", out)

    def test_blank_line_between_list_groups_is_dropped(self):
        out = from_gdoc_markdown(EXPORTED_LOOSE, LOCAL_TIGHT)
        self.assertIn("  - 練習自理。\n- **開學初期：**\n", out)

    def test_blank_line_after_heading_is_kept_when_local_has_one(self):
        out = from_gdoc_markdown(EXPORTED, LOCAL)
        self.assertIn("## 概述 Overview\n\n這場論壇", out)

    def test_blank_line_between_a_paragraph_and_its_list_is_dropped(self):
        out = from_gdoc_markdown(EXPORTED_LOOSE, LOCAL_TIGHT)
        self.assertIn("會議中完成以下分組：\n- **生活適應：**", out)

    def test_blank_line_before_a_heading_is_preserved(self):
        out = from_gdoc_markdown(EXPORTED_LOOSE, LOCAL_TIGHT)
        self.assertIn("本次會議由導師主持。\n\n## 內容詳述", out)


class ForwardConverterHeadings(unittest.TestCase):
    def test_bold_sub_bullets_survive_when_the_file_already_uses_headings(self):
        uploaded = gdoc.to_gdoc_markdown(LOCAL_TIGHT)
        self.assertIn("- **生活適應：**", uploaded)
        self.assertNotIn("### 生活適應：", uploaded)

    def test_theme_headings_are_untouched(self):
        uploaded = gdoc.to_gdoc_markdown(LOCAL_TIGHT)
        self.assertIn("### 暑期準備", uploaded)

    def test_legacy_bold_themes_are_still_promoted(self):
        uploaded = gdoc.to_gdoc_markdown(LOCAL_LEGACY)
        self.assertIn("### 論壇背景", uploaded)


class ForwardConverterMetadata(unittest.TestCase):
    def test_non_standard_frontmatter_keys_are_rendered(self):
        local = LOCAL.replace("gdoc_id:", "紀錄: 昀希爸爸\ngdoc_id:")
        uploaded = gdoc.to_gdoc_markdown(local)
        self.assertIn("**紀錄：** 昀希爸爸", uploaded)
        self.assertNotIn("gdoc_id", uploaded)

    def test_standard_keys_keep_their_chinese_labels(self):
        uploaded = gdoc.to_gdoc_markdown(LOCAL)
        self.assertIn("**講者：** 張三", uploaded)


# The doc's metadata block is the source of truth: a label renamed in Google
# Docs renames the field, a new label adds one, a removed label removes one.
EXPORTED_RENAMED = """# 高中校舍願景論壇

**導師：** 張三
**日期：** 2026-08-01
**紀錄：** 昀希爸爸

## 概述 Overview

這場論壇討論了校舍改建。

---
"""


class MetadataIsAuthoritative(unittest.TestCase):
    def setUp(self):
        self.out = from_gdoc_markdown(EXPORTED_RENAMED, LOCAL)
        self.meta = yaml.safe_load(self.out.split("---\n")[1])

    def test_unknown_label_becomes_a_frontmatter_field(self):
        self.assertEqual(self.meta["紀錄"], "昀希爸爸")

    def test_renamed_label_replaces_the_old_field(self):
        self.assertEqual(self.meta["導師"], "張三")
        self.assertNotIn("speaker", self.meta)

    def test_field_dropped_in_the_doc_is_dropped_locally(self):
        local = LOCAL.replace("speaker: 張三\n", "speaker: 張三\naudience: 家長\n")
        out = from_gdoc_markdown(EXPORTED_RENAMED, local)
        self.assertNotIn("audience", yaml.safe_load(out.split("---\n")[1]))

    def test_document_with_no_header_block_keeps_the_local_frontmatter(self):
        headless = "## 概述 Overview\n\n這場論壇討論了校舍改建。\n\n---\n"
        out = from_gdoc_markdown(headless, LOCAL)
        self.assertEqual(yaml.safe_load(out.split("---\n")[1]),
                         yaml.safe_load(LOCAL.split("---\n")[1]))

    def test_field_order_follows_the_document(self):
        self.assertEqual(list(self.meta), ["title", "導師", "date", "紀錄", "gdoc_id"])

    def test_gdoc_id_still_survives(self):
        self.assertEqual(self.meta["gdoc_id"], "1AbC_dEfGh")

    def test_unchanged_value_keeps_its_local_yaml_type(self):
        self.assertIn("date: 2026-08-01\n", self.out)


class MarkdownEscapes(unittest.TestCase):
    def test_escapes_google_docs_adds_are_removed(self):
        exported = EXPORTED.replace("這場論壇討論了校舍改建。", "會議結束\\~ 經費 3\\.5 萬")
        out = from_gdoc_markdown(exported, LOCAL)
        self.assertIn("會議結束~ 經費 3.5 萬", out)

    def test_escaped_bullet_text_still_matches_its_local_counterpart(self):
        exported = EXPORTED_NESTED.replace("家長會提出訴求", "家長會提出訴求\\!")
        out = from_gdoc_markdown(exported, LOCAL_NESTED)
        self.assertIn("\n- 家長會提出訴求!\n", out)
        self.assertNotIn("\\", out)


# --------------------------------------------------------------------------
# Regressions
# --------------------------------------------------------------------------

LOCAL_FULL_META = """---
title: 高中校舍願景論壇
speaker: 張三
audience: 家長
date: 2026-08-01
purpose: 說明改建計畫
gdoc_id: 1AbC_dEfGh
---

# Recording Summary

## 概述 Overview

這場論壇討論了校舍改建。

---
*Generated by video_summary using google/gemini-2.5-pro*
"""

# One label was retyped in Google Docs and lost its bold run.
EXPORTED_UNBOLDED_LABEL = """# 高中校舍願景論壇

講者： 張三
**對象：** 家長
**日期：** 2026-08-01
**目的：** 說明改建計畫

## 概述 Overview

這場論壇討論了校舍改建。

---
"""


class PartiallyFormattedHeader(unittest.TestCase):
    """A lost bold run must not take the rest of the frontmatter with it."""

    def test_a_label_that_lost_its_bold_is_still_read_as_metadata(self):
        out = from_gdoc_markdown(EXPORTED_UNBOLDED_LABEL, LOCAL_FULL_META)
        self.assertEqual(out, LOCAL_FULL_META)

    def test_the_fields_below_it_do_not_leak_into_the_body(self):
        out = from_gdoc_markdown(EXPORTED_UNBOLDED_LABEL, LOCAL_FULL_META)
        self.assertNotIn("**對象：**", out)
        self.assertNotIn("**目的：**", out)

    def test_an_unreadable_block_keeps_the_local_frontmatter(self):
        exported = (EXPORTED.replace("**講者：** 張三", "講者： 張三")
                            .replace("**日期：** 2026-08-01", "日期： 2026-08-01"))
        meta = yaml.safe_load(from_gdoc_markdown(exported, LOCAL).split("---\n")[1])
        self.assertEqual(meta, yaml.safe_load(LOCAL.split("---\n")[1]))

    def test_a_paragraph_that_is_not_metadata_stays_in_the_body(self):
        exported = EXPORTED.replace("**講者：** 張三\n**日期：** 2026-08-01",
                                    "開場：主持人致詞。")
        out = from_gdoc_markdown(exported, LOCAL)
        self.assertIn("開場：主持人致詞。", out)


class EmptyFrontmatterFields(unittest.TestCase):
    """gdoc.py cannot render a valueless field, so it must not be deleted."""

    def test_an_empty_field_survives_an_untouched_round_trip(self):
        local = LOCAL.replace("speaker: 張三\n", "speaker: 張三\nnotes: ''\n")
        exported = simulate_google_docs(gdoc.to_gdoc_markdown(local))
        self.assertEqual(from_gdoc_markdown(exported, local), local)

    def test_zero_and_false_are_values_and_are_rendered(self):
        local = LOCAL.replace("speaker: 張三\n", "count: 0\ndraft: false\nspeaker: 張三\n")
        uploaded = gdoc.to_gdoc_markdown(local)
        self.assertIn("**count：** 0", uploaded)
        self.assertIn("**draft：** False", uploaded)
        exported = simulate_google_docs(uploaded)
        self.assertEqual(from_gdoc_markdown(exported, local), local)


class FooterSurvivesInTheDoc(unittest.TestCase):
    """Google Docs sometimes keeps the italic generator line instead of eating it."""

    def _with_footer(self, copies=1):
        tail = "\n\n*Generated by video_summary using google/gemini-2.5-pro*"
        return EXPORTED.rstrip("\n") + tail * copies + "\n"

    def test_a_preserved_footer_is_not_duplicated(self):
        out = from_gdoc_markdown(self._with_footer(), LOCAL)
        self.assertEqual(out.count("*Generated by"), 1)
        self.assertEqual(out, LOCAL)

    def test_footers_stacked_by_an_earlier_sync_are_collapsed(self):
        out = from_gdoc_markdown(self._with_footer(copies=3), LOCAL)
        self.assertEqual(out.count("*Generated by"), 1)
        self.assertEqual(out, LOCAL)


class HardBreaks(unittest.TestCase):
    def test_trailing_backslash_line_breaks_do_not_reach_the_summary(self):
        exported = EXPORTED.replace("這場論壇討論了校舍改建。", "第一行\\\n第二行")
        out = from_gdoc_markdown(exported, LOCAL)
        self.assertIn("第一行\n第二行", out)
        self.assertNotIn("\\", out)


LOCAL_ORDERED = """---
title: 班親會
gdoc_id: 1AbC_dEfGh
---

# Recording Summary

## 結論 Conclusion
1. 先完成分組。
2. 再確認名單。
3. 最後回報。

---
*Generated by video_summary using google/gemini-2.5-pro*
"""

# Google Docs splits a numbered list into one paragraph per item.
EXPORTED_ORDERED = """# 班親會

## 結論 Conclusion

1. 先完成分組。

2. 再確認名單。

3. 最後回報。

---
"""


class OrderedLists(unittest.TestCase):
    def test_a_numbered_list_does_not_gain_blank_lines_on_every_sync(self):
        self.assertEqual(from_gdoc_markdown(EXPORTED_ORDERED, LOCAL_ORDERED), LOCAL_ORDERED)

    def test_a_numbered_item_keeps_its_own_number(self):
        exported = EXPORTED_ORDERED.replace("2. 再確認名單。", "2. 再確認名單與座位。")
        out = from_gdoc_markdown(exported, LOCAL_ORDERED)
        self.assertIn("\n2. 再確認名單與座位。\n", out)


LOCAL_LIST_THEN_HEADING = """---
title: 班親會
gdoc_id: 1AbC_dEfGh
---

# Recording Summary

## 分組 Groups
- 熟悉環境。
- 練習自理。
## 下一節 Next
會議結束。

---
*Generated by video_summary using google/gemini-2.5-pro*
"""

EXPORTED_LIST_THEN_HEADING = """# 班親會

## 分組 Groups

- 熟悉環境。

- 練習自理。

## 下一節 Next

會議結束。

---
"""


class BlankLineAfterAList(unittest.TestCase):
    def test_a_list_written_tight_against_the_next_block_stays_tight(self):
        self.assertEqual(
            from_gdoc_markdown(EXPORTED_LIST_THEN_HEADING, LOCAL_LIST_THEN_HEADING),
            LOCAL_LIST_THEN_HEADING)


LOCAL_ID_FIRST = LOCAL.replace(
    "title: 高中校舍願景論壇\n", "title: 高中校舍願景論壇\ngdoc_id: 1AbC_dEfGh\n"
).replace("date: 2026-08-01\ngdoc_id: 1AbC_dEfGh\n", "date: 2026-08-01\n")

LOCAL_YAML_STYLE = """---
title: 高中校舍願景論壇
# 8/1 論壇，家長會提供的紀錄
tags:
  - meeting
  - school
speaker: 張三
date: 2026-08-01
gdoc_id: 1AbC_dEfGh
---

# Recording Summary

## 概述 Overview

這場論壇討論了校舍改建。

---
*Generated by video_summary using google/gemini-2.5-pro*
"""


class FrontmatterFidelity(unittest.TestCase):
    def test_gdoc_id_keeps_the_position_it_holds_locally(self):
        self.assertEqual(from_gdoc_markdown(EXPORTED, LOCAL_ID_FIRST), LOCAL_ID_FIRST)

    def test_comments_and_block_style_survive_an_untouched_round_trip(self):
        exported = simulate_google_docs(gdoc.to_gdoc_markdown(LOCAL_YAML_STYLE))
        out = from_gdoc_markdown(exported, LOCAL_YAML_STYLE)
        self.assertIn("# 8/1 論壇，家長會提供的紀錄", out)
        self.assertEqual(out, LOCAL_YAML_STYLE)

    def test_an_edited_field_still_rewrites_the_frontmatter(self):
        exported = simulate_google_docs(gdoc.to_gdoc_markdown(LOCAL_YAML_STYLE))
        exported = exported.replace("**講者：** 張三", "**講者：** 李四")
        meta = yaml.safe_load(from_gdoc_markdown(exported, LOCAL_YAML_STYLE).split("---\n")[1])
        self.assertEqual(meta["speaker"], "李四")
        self.assertEqual(meta["tags"], ["meeting", "school"])

    def test_the_pipeline_and_the_sync_serialize_frontmatter_identically(self):
        data = {"title": "高中校舍願景論壇", "tags": ["meeting", "school"], "count": 0}
        self.assertEqual(cli.format_context_frontmatter(data), gdoc.dump_frontmatter(data))


class LegacyThemePromotion(unittest.TestCase):
    """A "###" outside the Detailed Breakdown must not switch promotion off."""

    def setUp(self):
        self.local = LOCAL_LEGACY.replace(
            "**3. 內容詳述**",
            "**2. 補充說明**\n\n### 場地\n\n在活動中心。\n\n**3. 內容詳述**")

    def test_bold_themes_are_still_promoted(self):
        self.assertIn("### 論壇背景", gdoc.to_gdoc_markdown(self.local))

    def test_their_detail_bullets_are_still_dedented(self):
        uploaded = gdoc.to_gdoc_markdown(self.local)
        self.assertIn("\n*   起因是校舍老舊", uploaded)
        self.assertNotIn("\n    *   起因是校舍老舊", uploaded)


class SectionAddedInTheDoc(unittest.TestCase):
    def setUp(self):
        exported = EXPORTED_LEGACY.replace(
            "\n---\n", "\n## 後續行動\n\n下次會議再議。\n\n---\n")
        self.out = from_gdoc_markdown(exported, LOCAL_LEGACY)

    def test_a_new_section_takes_the_shape_its_siblings_use(self):
        self.assertIn("**4. 後續行動**", self.out)
        self.assertNotIn("## 後續行動", self.out)

    def test_the_existing_sections_are_untouched(self):
        self.assertIn("**1. 概述**", self.out)
        self.assertIn("**3. 內容詳述**", self.out)

    def test_a_file_that_uses_real_headings_keeps_a_new_one(self):
        exported = EXPORTED_LOOSE.replace(
            "\n---\n", "\n## 後續行動\n\n下次會議再議。\n\n---\n")
        out = from_gdoc_markdown(exported, LOCAL_TIGHT)
        self.assertIn("## 後續行動", out)

    def test_its_bullets_are_siblings_rather_than_nested(self):
        # The section before this one ends at depth 1, and Google Docs exports
        # every item flat, so the depth must not carry across the new heading.
        exported = EXPORTED_LOOSE.replace(
            "\n---\n",
            "\n## 後續行動\n\n- 班代確認名單。\n- 財務組收費。\n\n---\n")
        out = from_gdoc_markdown(exported, LOCAL_TIGHT)
        self.assertIn("\n- 班代確認名單。\n- 財務組收費。\n", out)


class WriteSafety(unittest.TestCase):
    def setUp(self):
        self.dir = tempfile.mkdtemp()
        self.path = os.path.join(self.dir, "summary.md")
        with open(self.path, "w", encoding="utf-8") as f:
            f.write(LOCAL)
        self.out = io.StringIO()

    def tearDown(self):
        shutil.rmtree(self.dir)

    def _read(self):
        with open(self.path, encoding="utf-8") as f:
            return f.read()

    def test_a_failed_write_leaves_the_summary_intact(self):
        edited = EXPORTED.replace("校舍改建。", "校舍改建與經費。")
        with mock.patch.object(os, "replace", side_effect=OSError("disk full")):
            with self.assertRaises(OSError):
                gdoc_sync.sync(self.path, exporter=lambda _: edited,
                               confirm=lambda: True, out=self.out)
        self.assertEqual(self._read(), LOCAL)

    def test_a_failed_write_leaves_no_temp_file_behind(self):
        edited = EXPORTED.replace("校舍改建。", "校舍改建與經費。")
        with mock.patch.object(os, "replace", side_effect=OSError("disk full")):
            with self.assertRaises(OSError):
                gdoc_sync.sync(self.path, exporter=lambda _: edited,
                               confirm=lambda: True, out=self.out)
        self.assertEqual(os.listdir(self.dir), ["summary.md"])

    def test_the_file_mode_is_preserved(self):
        os.chmod(self.path, 0o640)
        edited = EXPORTED.replace("校舍改建。", "校舍改建與經費。")
        gdoc_sync.sync(self.path, exporter=lambda _: edited,
                       confirm=lambda: True, out=self.out)
        self.assertEqual(os.stat(self.path).st_mode & 0o777, 0o640)


class ErrorReporting(unittest.TestCase):
    def setUp(self):
        self.dir = tempfile.mkdtemp()
        self.path = os.path.join(self.dir, "summary.md")
        with open(self.path, "w", encoding="utf-8") as f:
            f.write(LOCAL)

    def tearDown(self):
        shutil.rmtree(self.dir)

    def _main(self, argv):
        err = io.StringIO()
        stderr, sys.stderr = sys.stderr, err
        try:
            return gdoc_sync.main(argv), err.getvalue()
        finally:
            sys.stderr = stderr

    def test_eof_on_the_prompt_declines_rather_than_raising(self):
        with mock.patch("builtins.input", side_effect=EOFError):
            self.assertFalse(gdoc_sync._ask())

    def test_a_missing_export_file_is_a_message_not_a_traceback(self):
        rc, err = self._main([self.path, "--from-file", os.path.join(self.dir, "nope.md")])
        self.assertEqual(rc, 1)
        self.assertIn("nope.md", err)

    def test_a_missing_summary_is_a_message_not_a_traceback(self):
        rc, err = self._main([os.path.join(self.dir, "gone.md"), "--doc-id", "abc"])
        self.assertEqual(rc, 1)
        self.assertIn("gone.md", err)

    def test_a_missing_gws_explains_itself(self):
        with mock.patch.object(gdoc_sync.subprocess, "run", side_effect=FileNotFoundError):
            with self.assertRaises(gdoc_sync.SyncError) as caught:
                gdoc_sync.export_doc("1AbC")
        self.assertIn("gws", str(caught.exception))

    def test_a_failed_export_explains_itself(self):
        error = subprocess.CalledProcessError(2, "gws")
        with mock.patch.object(gdoc_sync.subprocess, "run", side_effect=error):
            with self.assertRaises(gdoc_sync.SyncError) as caught:
                gdoc_sync.export_doc("1AbC")
        self.assertIn("1AbC", str(caught.exception))


class TestFileLayout(unittest.TestCase):
    def test_the_unittest_main_guard_is_the_last_thing_in_the_file(self):
        # Anywhere else and a direct `python3 tests/test_gdoc_sync.py` exits
        # before the classes below it are even defined.
        with open(__file__, encoding="utf-8") as f:
            source = f.read()
        self.assertTrue(
            source.rstrip().endswith('if __name__ == "__main__":\n    unittest.main()'))

if __name__ == "__main__":
    unittest.main()
